import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/utils/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import JSZip from "jszip";

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await requireAuth(req);
  if (!user) return NextResponse.json({ data: null, error: "Unauthorized" }, { status: 401 });

  const { id: projectId } = await params;
  const admin = createAdminClient();

  const { data: project } = await admin
    .from("projects").select("id, name, description, metadata")
    .eq("id", projectId).eq("user_id", user.id).single();
  if (!project) return NextResponse.json({ data: null, error: "Project not found" }, { status: 404 });

  const { data: files } = await admin
    .from("project_files").select("path, content, language")
    .eq("project_id", projectId).eq("is_deleted", false);

  if (!files || files.length === 0) {
    return NextResponse.json({ data: null, error: "No files to export" }, { status: 400 });
  }

  const zip = new JSZip();
  const manifest: Array<{ path: string; language: string; size: number }> = [];

  for (const file of files) {
    const content = (file.content ?? "") as string;
    const cleanPath = (file.path as string).startsWith("/") ? (file.path as string).slice(1) : (file.path as string);
    zip.file(cleanPath, content);
    manifest.push({ path: cleanPath, language: (file.language ?? "text") as string, size: content.length });
  }

  // Add manifest
  zip.file("_agentforge_manifest.json", JSON.stringify({
    project_id:   projectId,
    project_name: project.name,
    exported_at:  new Date().toISOString(),
    file_count:   files.length,
    files:        manifest,
  }, null, 2));

  // Add setup docs
  zip.file("_agentforge_setup.md", `# ${project.name} — Setup\n\nGenerated by AgentForge.\n\n## Quick Start\n\n\`\`\`bash\nnpm install\ncp .env.example .env.local\n# Fill in .env.local with your credentials\nnpm run dev\n\`\`\`\n`);

  const zipBuffer = await zip.generateAsync({ type: "uint8array", compression: "DEFLATE" });

  const projectName = (project.name as string).replace(/[^a-z0-9-]/gi, "-").toLowerCase();
  const filename = `${projectName}-${new Date().toISOString().split("T")[0]}.zip`;

  // Record export (non-blocking)
  try {
    await admin.from("exports").insert({
      project_id:   projectId,
      storage_path: `exports/${projectId}/${filename}`,
      file_count:   files.length,
      size_bytes:   zipBuffer.length,
      manifest:     { files: manifest },
    });
  } catch { /* non-blocking */ }

  return new Response(zipBuffer.buffer as ArrayBuffer, {
    headers: {
      "Content-Type":        "application/zip",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length":      String(zipBuffer.byteLength),
    },
  });
}
