import { generateStructured } from "@/lib/ai/provider-router";
import { type AgentContext, type AgentResult } from "@/types/agent";
import { createAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";

const FileSchema = z.object({
  path:        z.string().min(1),
  content:     z.string().min(10),
  language:    z.string().default("ts"),
  description: z.string().optional(),
});

const BackendOutputSchema = z.object({
  files:    z.array(FileSchema),
  env_vars: z.array(z.object({
    key:         z.string(),
    description: z.string(),
    required:    z.boolean(),
  })).optional().default([]),
  notes: z.string().optional(),
});

export type BackendOutput = z.infer<typeof BackendOutputSchema>;

const SYSTEM = `You are the Backend Agent for AgentForge. Given a product brief and architecture, generate complete backend code.

Generate these file types:
- app/api/[resource]/route.ts — REST API routes with GET/POST/PATCH/DELETE
- app/api/auth/ — auth-related routes (signout, callback)
- lib/actions/ — Next.js Server Actions for mutations
- lib/validators/ — Zod schemas for API input validation
- lib/services/ — business logic services
- middleware.ts — auth guards, rate limiting

Rules:
- Use Next.js 15 App Router Route Handlers (not pages/api)
- TypeScript with strict types
- Zod validation on ALL API inputs
- requireAuth() check on every protected route
- Return NextResponse.json() consistently
- Use Supabase admin client for server-side DB operations
- Row Level Security enforced — never bypass RLS in user-facing routes
- Rate limit expensive operations
- Generate 6-12 files covering all API endpoints in the architecture
- Each file must be complete and compilable

Return ONLY valid JSON matching the BackendOutput schema.`;

async function writeFiles(
  projectId: string,
  runId: string,
  output: BackendOutput
): Promise<string[]> {
  const admin = createAdminClient();
  const written: string[] = [];

  for (const file of output.files) {
    if (!file.path?.trim() || !file.content?.trim() || file.content.length < 10) continue;

    const cleanPath = file.path.startsWith("/") ? file.path.slice(1) : file.path;

    const { error } = await admin.from("project_files").upsert(
      {
        project_id: projectId,
        path:       cleanPath,
        content:    file.content,
        language:   file.language ?? "ts",
        agent_id:   "backend",
        provenance: {
          agent:        "backend",
          run_id:       runId,
          description:  file.description ?? "Generated by Backend Agent",
          generated_at: new Date().toISOString(),
        },
        is_deleted: false,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "project_id,path", ignoreDuplicates: false }
    );

    if (error) {
      console.error(`[backend] Failed to write ${cleanPath}:`, error.message);
    } else {
      written.push(cleanPath);
    }
  }

  // Write env vars as .env.example
  if (output.env_vars && output.env_vars.length > 0) {
    const envContent = output.env_vars
      .map(v => `${v.key}=${v.required ? "REQUIRED" : "optional"} # ${v.description}`)
      .join("\n");
    const cleanPath = ".env.example";
    await admin.from("project_files").upsert(
      {
        project_id: projectId,
        path:       cleanPath,
        content:    `# Environment Variables\n# Copy to .env.local and fill in values\n\n${envContent}\n`,
        language:   "env",
        agent_id:   "backend",
        provenance: { agent: "backend", run_id: runId, generated_at: new Date().toISOString() },
        is_deleted: false,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "project_id,path", ignoreDuplicates: false }
    );
    written.push(cleanPath);
  }

  return written;
}

export async function runBackend(ctx: AgentContext): Promise<AgentResult<BackendOutput>> {
  const start = Date.now();
  const brief = JSON.stringify(ctx.inputs?.productBrief ?? ctx.inputs?.plan ?? {});
  const arch  = JSON.stringify(ctx.inputs?.architecture ?? {});

  const result = await generateStructured({
    taskType:     "backendCode",
    systemPrompt: SYSTEM,
    userMessage:  `Generate backend API code for this product.\n\nProduct Brief: ${brief.slice(0, 3000)}\n\nArchitecture: ${arch.slice(0, 2000)}`,
    schema:       BackendOutputSchema,
    ctx,
  });

  const written = await writeFiles(ctx.projectId, ctx.runId, result.data);

  if (written.length) console.log(`[backend] wrote ${written.length} files: ${written.join(", ")}`);

  return {
    success: true,
    output:  result.data,
    errors:  [],
    metadata: {
      provider:     result.provider,
      model:        result.model,
      tokens_used:  result.usage.total_tokens,
      latency_ms:   Date.now() - start,
      provenance: {
        agent:        "backend",
        model:        result.model,
        provider:     result.provider,
        run_id:       ctx.runId,
        task_id:      ctx.taskId,
        generated_at: new Date().toISOString(),
        version:      1,
      },
    },
  };
}
