import { generateStructured } from "@/lib/ai/provider-router";
import { type AgentContext, type AgentResult } from "@/types/agent";
import { createAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";

const TableSchema = z.object({
  name: z.string(),
  columns: z.array(z.object({ name: z.string(), type: z.string(), constraints: z.string() })),
  rls_policies: z.array(z.object({ name: z.string(), operation: z.string(), definition: z.string() })),
});

const DatabaseOutputSchema = z.object({
  tables: z.array(TableSchema),
  migration_sql: z.string(),
  seed_sql: z.string().optional(),
  indexes: z.array(z.string()),
  notes: z.string().optional(),
});

export type DatabaseOutput = z.infer<typeof DatabaseOutputSchema>;

const SYSTEM = `You are the Database Agent for AgentForge. Given a product brief and domain model, generate a complete Supabase/PostgreSQL database schema.

Produce:
- Table definitions with proper types and constraints
- Row Level Security (RLS) policies for every table
- Indexes for foreign keys and frequently queried columns
- Complete migration SQL (CREATE TABLE IF NOT EXISTS, RLS enable, policies)
- Optional seed data for development

RLS POLICY TEMPLATE — use this exact pattern for every user-owned table:
  -- Read own rows
  CREATE POLICY "{table}_users_read_own" ON {table}
    FOR SELECT USING (auth.uid() = user_id);
  -- Insert as self
  CREATE POLICY "{table}_users_insert_own" ON {table}
    FOR INSERT WITH CHECK (auth.uid() = user_id);
  -- Update own rows
  CREATE POLICY "{table}_users_update_own" ON {table}
    FOR UPDATE USING (auth.uid() = user_id);
  -- Delete own rows
  CREATE POLICY "{table}_users_delete_own" ON {table}
    FOR DELETE USING (auth.uid() = user_id);

For shared/public tables (e.g., categories, plans, public_profiles), use:
  CREATE POLICY "{table}_public_read" ON {table} FOR SELECT USING (true);
  -- Write still requires auth:
  CREATE POLICY "{table}_auth_write" ON {table}
    FOR ALL USING (auth.uid() IS NOT NULL);

For join/pivot tables (e.g., user_roles, team_members), scope to the parent:
  CREATE POLICY "{table}_member_read" ON {table}
    FOR SELECT USING (auth.uid() = user_id OR auth.uid() IN (
      SELECT owner_id FROM parent_table WHERE id = {table}.parent_id
    ));

ADDITIONAL RULES:
- Always use UUID primary keys with gen_random_uuid() (preferred over uuid_generate_v4())
- Always include created_at TIMESTAMPTZ NOT NULL DEFAULT NOW() and updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
- Enable RLS on every user-facing table: ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
- Use proper CASCADE delete rules on foreign keys
- Include a trigger for updated_at auto-update using handle_updated_at()
- Migration must be idempotent (IF NOT EXISTS, OR REPLACE, IF NOT EXISTS for policies)
- Generate SQL that runs cleanly in Supabase SQL Editor

Return ONLY valid JSON matching the DatabaseOutput schema.`;

async function writeFiles(
  projectId: string,
  runId: string,
  output: DatabaseOutput
): Promise<string[]> {
  const admin = createAdminClient();
  const written: string[] = [];

  const migrationContent = `-- Generated by Database Agent
-- Run this in your Supabase SQL Editor

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Auto-update trigger function
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Schema
${output.migration_sql}

-- Indexes
${output.indexes.join("\n")}
${output.seed_sql ? `\n-- Seed Data\n${output.seed_sql}` : ""}
`;

  await admin.from("project_files").upsert(
    {
      project_id: projectId,
      path: "supabase/migrations/001_schema.sql",
      content: migrationContent,
      language: "sql",
      agent_id: "database",
      provenance: { agent: "database", run_id: runId, generated_at: new Date().toISOString() },
      is_deleted: false,
      updated_at: new Date().toISOString(),
    },
    { onConflict: "project_id,path", ignoreDuplicates: false }
  );
  written.push("supabase/migrations/001_schema.sql");

  const typeContent = `// Database types — generated by Database Agent
// Re-export from your Supabase generated types or use these as a base

${output.tables.map(table => `export interface ${toPascalCase(table.name)} {\n${table.columns.map(col => `  ${col.name}: ${sqlTypeToTs(col.type)};`).join("\n")}\n}`).join("\n\n")}
`;

  await admin.from("project_files").upsert(
    {
      project_id: projectId,
      path: "types/database.ts",
      content: typeContent,
      language: "typescript",
      agent_id: "database",
      provenance: { agent: "database", run_id: runId, generated_at: new Date().toISOString() },
      is_deleted: false,
      updated_at: new Date().toISOString(),
    },
    { onConflict: "project_id,path", ignoreDuplicates: false }
  );
  written.push("types/database.ts");

  return written;
}

function toPascalCase(str: string): string {
  return str.replace(/(^|_)([a-z])/g, (_, __, c) => c.toUpperCase());
}

function sqlTypeToTs(sqlType: string): string {
  const t = sqlType.toLowerCase();
  if (t.includes("uuid")) return "string";
  if (t.includes("text") || t.includes("varchar") || t.includes("char")) return "string";
  if (t.includes("int") || t.includes("numeric") || t.includes("float") || t.includes("decimal")) return "number";
  if (t.includes("bool")) return "boolean";
  if (t.includes("timestamp") || t.includes("date")) return "string";
  if (t.includes("jsonb") || t.includes("json")) return "Record<string, unknown>";
  return "unknown";
}

export async function runDatabase(ctx: AgentContext): Promise<AgentResult<DatabaseOutput>> {
  const start = Date.now();
  const brief = JSON.stringify(ctx.inputs.productBrief ?? ctx.inputs.plan ?? {});
  const arch = JSON.stringify(ctx.inputs.architecture ?? {});

  const result = await generateStructured({
    taskType: "database",
    systemPrompt: SYSTEM,
    userMessage: `Generate a complete database schema for this product.\n\nProduct Brief: ${brief.slice(0, 3000)}\n\nArchitecture (use domain_model as the entity source of truth): ${arch.slice(0, 2000)}`,
    schema: DatabaseOutputSchema,
    ctx,
  });

  await writeFiles(ctx.projectId, ctx.runId, result.data);

  return {
    success: true,
    output: result.data,
    errors: [],
    metadata: {
      provider: result.provider,
      model: result.model,
      tokens_used: result.usage.total_tokens,
      latency_ms: Date.now() - start,
      provenance: {
        agent: "database",
        model: result.model,
        provider: result.provider,
        run_id: ctx.runId,
        task_id: ctx.taskId,
        generated_at: new Date().toISOString(),
        version: 1,
      },
    },
  };
}
