import { generateStructured } from "@/lib/ai/provider-router";
import { type AgentContext, type AgentResult } from "@/types/agent";
import { createAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";

const TableSchema = z.object({
  name: z.string(),
  columns: z.array(z.object({ name: z.string(), type: z.string(), constraints: z.string() })),
  rls_policies: z.array(z.object({ name: z.string(), operation: z.string(), definition: z.string() })),
});

const DatabaseOutputSchema = z.object({
  tables: z.array(TableSchema),
  migration_sql: z.string(),
  seed_sql: z.string().optional(),
  indexes: z.array(z.string()),
  notes: z.string().optional(),
});

export type DatabaseOutput = z.infer<typeof DatabaseOutputSchema>;

const SYSTEM = `You are the Database Agent for AgentForge. Given a product brief and domain model, generate a complete Supabase/PostgreSQL database schema.

Produce:
- Table definitions with proper types and constraints
- Row Level Security (RLS) policies for every table
- Indexes for foreign keys and frequently queried columns
- Complete migration SQL (CREATE TABLE IF NOT EXISTS, RLS enable, policies)
- Optional seed data for development

Rules:
- Always use UUID primary keys with uuid_generate_v4()
- Always include created_at and updated_at TIMESTAMPTZ columns
- Enable RLS on every user-facing table
- Write RLS policies that scope data to auth.uid()
- Use proper CASCADE delete rules
- Include a trigger for updated_at auto-update
- Migration must be idempotent (IF NOT EXISTS, OR REPLACE)
- Generate SQL that runs in Supabase SQL Editor

Return ONLY valid JSON matching the DatabaseOutput schema.`;

async function writeFiles(
  projectId: string,
  runId: string,
  output: DatabaseOutput
): Promise<string[]> {
  const admin = createAdminClient();
  const written: string[] = [];

  // Main migration file
  const migrationContent = `-- Generated by Database Agent
-- Run this in your Supabase SQL Editor

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Auto-update trigger function
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Schema
${output.migration_sql}

-- Indexes
${output.indexes.join("\n")}
${output.seed_sql ? `\n-- Seed Data\n${output.seed_sql}` : ""}
`;

  await admin.from("project_files").upsert(
    {
      project_id: projectId,
      path: "supabase/migrations/001_schema.sql",
      content: migrationContent,
      language: "sql",
      agent_id: "database",
      provenance: { agent: "database", run_id: runId, generated_at: new Date().toISOString() },
      is_deleted: false,
      updated_at: new Date().toISOString(),
    },
    { onConflict: "project_id,path", ignoreDuplicates: false }
  );
  written.push("supabase/migrations/001_schema.sql");

  // TypeScript types from schema
  const typeContent = `// Database types — generated by Database Agent
// Re-export from your Supabase generated types or use these as a base

${output.tables.map(table => `export interface ${toPascalCase(table.name)} {
${table.columns.map(col => `  ${col.name}: ${sqlTypeToTs(col.type)};`).join("\n")}
}`).join("\n\n")}
`;

  await admin.from("project_files").upsert(
    {
      project_id: projectId,
      path: "types/database.ts",
      content: typeContent,
      language: "typescript",
      agent_id: "database",
      provenance: { agent: "database", run_id: runId, generated_at: new Date().toISOString() },
      is_deleted: false,
      updated_at: new Date().toISOString(),
    },
    { onConflict: "project_id,path", ignoreDuplicates: false }
  );
  written.push("types/database.ts");

  return written;
}

function toPascalCase(str: string): string {
  return str.replace(/(^|_)([a-z])/g, (_, __, c) => c.toUpperCase());
}

function sqlTypeToTs(sqlType: string): string {
  const t = sqlType.toLowerCase();
  if (t.includes("uuid")) return "string";
  if (t.includes("text") || t.includes("varchar") || t.includes("char")) return "string";
  if (t.includes("int") || t.includes("numeric") || t.includes("float") || t.includes("decimal")) return "number";
  if (t.includes("bool")) return "boolean";
  if (t.includes("timestamp") || t.includes("date")) return "string";
  if (t.includes("jsonb") || t.includes("json")) return "Record<string, unknown>";
  return "unknown";
}

export async function runDatabase(ctx: AgentContext): Promise<AgentResult<DatabaseOutput>> {
  const start = Date.now();
  const brief = JSON.stringify(ctx.inputs.productBrief ?? ctx.inputs.plan ?? {});
  const arch = JSON.stringify(ctx.inputs.architecture ?? {});

  const result = await generateStructured({
    taskType: "database",
    systemPrompt: SYSTEM,
    userMessage: `Generate a complete database schema for this product.\n\nProduct Brief: ${brief.slice(0, 3000)}\n\nArchitecture: ${arch.slice(0, 2000)}`,
    schema: DatabaseOutputSchema,
    ctx,
  });

  await writeFiles(ctx.projectId, ctx.runId, result.data);

  return {
    success: true,
    output: result.data,
    errors: [],
    metadata: {
      provider: result.provider,
      model: result.model,
      tokens_used: result.usage.total_tokens,
      latency_ms: Date.now() - start,
      provenance: {
        agent: "database",
        model: result.model,
        provider: result.provider,
        run_id: ctx.runId,
        task_id: ctx.taskId,
        generated_at: new Date().toISOString(),
        version: 1,
      },
    },
  };
}
