import { generateStructured } from "@/lib/ai/provider-router";
import { type AgentContext, type AgentResult } from "@/types/agent";
import { createAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";

const FileSchema = z.object({
  path:        z.string().min(1),
  content:     z.string().min(10),
  language:    z.string().default("tsx"),
  description: z.string().optional(),
});

const FrontendOutputSchema = z.object({
  files:        z.array(FileSchema),
  dependencies: z.array(z.string()).optional().default([]),
  notes:        z.string().optional(),
});

export type FrontendOutput = z.infer<typeof FrontendOutputSchema>;

const SYSTEM = `You are the Frontend Agent for AgentForge. Given a product brief and architecture, generate complete, production-ready frontend code.

Generate these file types:
- app/page.tsx (landing/home)
- app/layout.tsx (root layout with providers)
- app/(auth)/login/page.tsx and signup/page.tsx
- app/(dashboard)/dashboard/page.tsx
- Key feature pages based on the brief
- components/ui/ — Button, Input, Card, Modal, etc.
- components/[feature]/ — feature-specific components
- hooks/use[Feature].ts — custom hooks

Rules:
- Use Next.js 15 App Router with TypeScript
- Tailwind CSS for styling
- Server Components where possible, Client Components only when needed
- Supabase for auth and data
- Zod for form validation
- Each file must be complete and compilable
- Import paths use @/ alias
- Keep each file focused and under 200 lines
- Generate 8-15 files covering the core user flows

Return ONLY valid JSON matching the FrontendOutput schema.`;

async function writeFiles(
  projectId: string,
  runId: string,
  output: FrontendOutput
): Promise<string[]> {
  const admin = createAdminClient();
  const written: string[] = [];

  for (const file of output.files) {
    // Guard: skip empty or invalid files
    if (!file.path?.trim() || !file.content?.trim() || file.content.length < 10) continue;

    const cleanPath = file.path.startsWith("/") ? file.path.slice(1) : file.path;

    // Use only columns that exist in the schema.
    // run_id and description live inside provenance JSONB.
    const { error } = await admin.from("project_files").upsert(
      {
        project_id:  projectId,
        path:        cleanPath,
        content:     file.content,
        language:    file.language ?? "tsx",
        agent_id:    "frontend",
        provenance:  {
          agent:       "frontend",
          run_id:      runId,
          description: file.description ?? "Generated by Frontend Agent",
          generated_at: new Date().toISOString(),
        },
        is_deleted:  false,
        updated_at:  new Date().toISOString(),
      },
      // Match the actual partial unique index: (project_id, path) WHERE version_id IS NULL
      // PostgREST requires the constraint name or column list — use ignoreDuplicates:false
      // to trigger an UPDATE on conflict.
      { onConflict: "project_id,path", ignoreDuplicates: false }
    );

    if (error) {
      console.error(`[frontend] Failed to write ${cleanPath}:`, error.message);
    } else {
      written.push(cleanPath);
    }
  }

  // Write dependency list as a markdown doc
  if (output.dependencies && output.dependencies.length > 0) {
    const cleanPath = "docs/frontend-dependencies.md";
    await admin.from("project_files").upsert(
      {
        project_id: projectId,
        path:       cleanPath,
        content:    `# Frontend Dependencies\n\nAdd these to package.json:\n\n\`\`\`\n${output.dependencies.join("\n")}\n\`\`\`\n`,
        language:   "markdown",
        agent_id:   "frontend",
        provenance: { agent: "frontend", run_id: runId, generated_at: new Date().toISOString() },
        is_deleted: false,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "project_id,path", ignoreDuplicates: false }
    );
    written.push(cleanPath);
  }

  return written;
}

export async function runFrontend(ctx: AgentContext): Promise<AgentResult<FrontendOutput>> {
  const start = Date.now();
  const brief = JSON.stringify(ctx.inputs?.productBrief ?? ctx.inputs?.plan ?? {});
  const arch  = JSON.stringify(ctx.inputs?.architecture ?? {});

  const result = await generateStructured({
    taskType:     "frontendCode",
    systemPrompt: SYSTEM,
    userMessage:  `Generate frontend code for this product.\n\nProduct Brief: ${brief.slice(0, 3000)}\n\nArchitecture: ${arch.slice(0, 2000)}`,
    schema:       FrontendOutputSchema,
    ctx,
  });

  const written = await writeFiles(ctx.projectId, ctx.runId, result.data);

  if (written.length) console.log(`[frontend] wrote ${written.length} files: ${written.join(", ")}`);

  return {
    success: true,
    output:  result.data,
    errors:  [],
    metadata: {
      provider:     result.provider,
      model:        result.model,
      tokens_used:  result.usage.total_tokens,
      latency_ms:   Date.now() - start,
      provenance: {
        agent:        "frontend",
        model:        result.model,
        provider:     result.provider,
        run_id:       ctx.runId,
        task_id:      ctx.taskId,
        generated_at: new Date().toISOString(),
        version:      1,
      },
    },
  };
}
