import { generateStructured } from "@/lib/ai/provider-router";
import { type AgentContext, type AgentResult } from "@/types/agent";
import { createAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";

const FileSchema = z.object({
  path:        z.string().min(1),
  content:     z.string().min(10),
  language:    z.string().default("tsx"),
  description: z.string().optional(),
});

const FrontendOutputSchema = z.object({
  files:        z.array(FileSchema),
  dependencies: z.array(z.string()).optional().default([]),
  notes:        z.string().optional(),
});

export type FrontendOutput = z.infer<typeof FrontendOutputSchema>;

const SYSTEM = `You are the Frontend Agent for AgentForge. Given a product brief and architecture, generate complete, production-ready frontend code.

Generate these file types:
- app/page.tsx (landing/home)
- app/layout.tsx (root layout with providers)
- app/(auth)/login/page.tsx and signup/page.tsx
- app/(dashboard)/dashboard/page.tsx
- Key feature pages based on the brief
- components/ui/ — Button, Input, Card, Modal, etc.
- components/[feature]/ — feature-specific components
- hooks/use[Feature].ts — custom hooks

ARCHITECTURE CONTRACT — follow exactly:
- Use ONLY the routes defined in api_plan from the architecture JSON. Do not invent new endpoints.
- Use ONLY the entities in domain_model for TypeScript interfaces. Do not define new data shapes.
- Auth pattern: always use @supabase/ssr (NOT @supabase/auth-helpers — that package is deprecated).
- Every page requiring auth must call createServerClient(), check the session, and redirect to /login if null.
- Do not generate placeholder or "TODO" components. Every component must render real data from the API routes in the architecture.

CODE QUALITY RULES:
- Next.js 15 App Router with TypeScript strict mode
- Tailwind CSS for all styling — no inline styles, no CSS modules
- Server Components by default; add "use client" only when using hooks or browser APIs
- Every fetch call must handle loading state and error state
- Form submissions use Server Actions or fetch to the API routes — never direct DB access from client
- Import paths use @/ alias exclusively
- Keep each file under 200 lines; split into sub-components if needed
- Generate 8–15 files covering the core user flows

Return ONLY valid JSON matching the FrontendOutput schema.`;

async function writeFiles(
  projectId: string,
  runId: string,
  output: FrontendOutput
): Promise<string[]> {
  const admin = createAdminClient();
  const written: string[] = [];

  for (const file of output.files) {
    if (!file.path?.trim() || !file.content?.trim() || file.content.length < 10) continue;

    const cleanPath = file.path.startsWith("/") ? file.path.slice(1) : file.path;

    const { error } = await admin.from("project_files").upsert(
      {
        project_id:  projectId,
        path:        cleanPath,
        content:     file.content,
        language:    file.language ?? "tsx",
        agent_id:    "frontend",
        provenance:  {
          agent:        "frontend",
          run_id:       runId,
          description:  file.description ?? "Generated by Frontend Agent",
          generated_at: new Date().toISOString(),
        },
        is_deleted:  false,
        updated_at:  new Date().toISOString(),
      },
      { onConflict: "project_id,path", ignoreDuplicates: false }
    );

    if (error) {
      console.error(`[frontend] Failed to write ${cleanPath}:`, error.message);
    } else {
      written.push(cleanPath);
    }
  }

  if (output.dependencies && output.dependencies.length > 0) {
    const cleanPath = "docs/frontend-dependencies.md";
    await admin.from("project_files").upsert(
      {
        project_id: projectId,
        path:       cleanPath,
        content:    `# Frontend Dependencies\n\nAdd these to package.json:\n\n\`\`\`\n${output.dependencies.join("\n")}\n\`\`\`\n`,
        language:   "markdown",
        agent_id:   "frontend",
        provenance: { agent: "frontend", run_id: runId, generated_at: new Date().toISOString() },
        is_deleted: false,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "project_id,path", ignoreDuplicates: false }
    );
    written.push(cleanPath);
  }

  return written;
}

export async function runFrontend(ctx: AgentContext): Promise<AgentResult<FrontendOutput>> {
  const start = Date.now();
  const brief = JSON.stringify(ctx.inputs?.productBrief ?? ctx.inputs?.plan ?? {});
  const arch  = JSON.stringify(ctx.inputs?.architecture ?? {});

  const result = await generateStructured({
    taskType:     "frontendCode",
    systemPrompt: SYSTEM,
    userMessage:  `Generate frontend code for this product.\n\nProduct Brief: ${brief.slice(0, 3000)}\n\nArchitecture (source of truth for routes, entities, and auth pattern): ${arch.slice(0, 3000)}`,
    schema:       FrontendOutputSchema,
    ctx,
  });

  const written = await writeFiles(ctx.projectId, ctx.runId, result.data);

  if (written.length) console.log(`[frontend] wrote ${written.length} files: ${written.join(", ")}`);

  return {
    success: true,
    output:  result.data,
    errors:  [],
    metadata: {
      provider:     result.provider,
      model:        result.model,
      tokens_used:  result.usage.total_tokens,
      latency_ms:   Date.now() - start,
      provenance: {
        agent:        "frontend",
        model:        result.model,
        provider:     result.provider,
        run_id:       ctx.runId,
        task_id:      ctx.taskId,
        generated_at: new Date().toISOString(),
        version:      1,
      },
    },
  };
}
