import { generateStructured } from "@/lib/ai/provider-router";
import { type AgentContext, type AgentResult } from "@/types/agent";
import { createAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";

const UIUXOutputSchema = z.object({
  color_palette: z.object({
    primary: z.string(),
    secondary: z.string(),
    accent: z.string(),
    background: z.string(),
    surface: z.string(),
    text: z.string(),
    muted: z.string(),
  }),
  typography: z.object({
    font_family: z.string(),
    heading_scale: z.array(z.string()),
    body_size: z.string(),
  }),
  design_tokens: z.array(z.object({
    name: z.string(),
    value: z.string(),
    category: z.string(),
  })),
  screens: z.array(z.object({
    name: z.string(),
    route: z.string(),
    description: z.string(),
    components: z.array(z.string()),
  })),
  component_library: z.array(z.object({
    name: z.string(),
    props: z.array(z.string()),
    description: z.string(),
  })),
  tailwind_config_additions: z.string(),
  globals_css_additions: z.string(),
  notes: z.string().optional(),
});

export type UIUXOutput = z.infer<typeof UIUXOutputSchema>;

const SYSTEM = `You are the UI/UX Agent for AgentForge. Given a product brief and architecture, produce:
1. A complete color palette and typography system
2. Design tokens as CSS custom properties
3. Screen inventory with routes and component lists
4. Component library spec
5. Tailwind config additions (colors, fonts, spacing)
6. globals.css additions (CSS variables, base styles)

Design principles: clean, modern, accessible. Default to dark theme with violet/indigo accents unless brief specifies otherwise.
Return ONLY valid JSON matching the UIUXOutput schema.`;

async function writeFiles(
  projectId: string,
  runId: string,
  output: UIUXOutput,
  ctx: AgentContext
): Promise<string[]> {
  const admin = createAdminClient();
  const written: string[] = [];

  const tailwindConfig = `import type { Config } from "tailwindcss";
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "${output.color_palette.primary}",
        secondary: "${output.color_palette.secondary}",
        accent: "${output.color_palette.accent}",
        background: "${output.color_palette.background}",
        surface: "${output.color_palette.surface}",
        muted: "${output.color_palette.muted}",
      },
      fontFamily: {
        sans: ["${output.typography.font_family}", "system-ui", "sans-serif"],
      },
      ${output.tailwind_config_additions}
    },
  },
  plugins: [],
};
export default config;`;

  const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
${output.design_tokens.map(t => `  --${t.name}: ${t.value};`).join("\n")}
}

@layer base {
  body {
    background-color: ${output.color_palette.background};
    color: ${output.color_palette.text};
    font-family: ${output.typography.font_family}, system-ui, sans-serif;
  }
  h1, h2, h3, h4, h5, h6 {
    font-weight: 600;
    letter-spacing: -0.025em;
  }
}

${output.globals_css_additions}`;

  const designSystem = `// Design System — generated by UI/UX Agent
// Color Palette
export const colors = ${JSON.stringify(output.color_palette, null, 2)};

// Typography
export const typography = ${JSON.stringify(output.typography, null, 2)};

// Design Tokens
export const tokens = ${JSON.stringify(output.design_tokens, null, 2)};

// Screen Inventory
export const screens = ${JSON.stringify(output.screens, null, 2)};

// Component Library
export const components = ${JSON.stringify(output.component_library, null, 2)};
`;

  const files = [
    { path: "tailwind.config.ts", content: tailwindConfig, language: "typescript" },
    { path: "app/globals.css", content: globalsCss, language: "css" },
    { path: "lib/design-system.ts", content: designSystem, language: "typescript" },
  ];

  for (const file of files) {
    await admin.from("project_files").upsert(
      {
        project_id: projectId,
        path: file.path,
        content: file.content,
        language: file.language,
        agent_id: "uiux",
        provenance: {
          agent: "uiux",
          run_id: runId,
          generated_at: new Date().toISOString(),
        },
        is_deleted: false,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "project_id,path", ignoreDuplicates: false }
    );
    written.push(file.path);
  }

  return written;
}

export async function runUIUX(ctx: AgentContext): Promise<AgentResult<UIUXOutput>> {
  const start = Date.now();
  const brief = JSON.stringify(ctx.inputs.productBrief ?? ctx.inputs.plan ?? {});

  const result = await generateStructured({
    taskType: "uiux",
    systemPrompt: SYSTEM,
    userMessage: `Create a complete UI/UX design system for this product: ${brief}`,
    schema: UIUXOutputSchema,
    ctx,
  });

  const written = await writeFiles(ctx.projectId, ctx.runId, result.data, ctx);

  return {
    success: true,
    output: result.data,
    errors: [],
    metadata: {
      provider: result.provider,
      model: result.model,
      tokens_used: result.usage.total_tokens,
      latency_ms: Date.now() - start,
      provenance: {
        agent: "uiux",
        model: result.model,
        provider: result.provider,
        run_id: ctx.runId,
        task_id: ctx.taskId,
        generated_at: new Date().toISOString(),
        version: 1,
      },
    },
  };
}
