import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireAuth } from "@/lib/utils/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { Octokit } from "@octokit/rest";
import { decryptSecret } from "@/lib/utils/crypto";
import { rateLimit } from "@/lib/rate-limit";

const PushSchema = z.object({
  repoName:    z.string().min(1).max(100).regex(/^[a-zA-Z0-9_.-]+$/, "Invalid repo name"),
  description: z.string().max(300).optional(),
  isPrivate:   z.boolean().default(true),
  branch:      z.string().default("main"),
});

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await requireAuth(req);
  if (!user) return NextResponse.json({ data: null, error: "Unauthorized" }, { status: 401 });

  const { id: projectId } = await params;

  const rl = rateLimit(`github:${user.id}`, { limit: 5, windowMs: 60 * 60 * 1000 });
  if (!rl.success) return NextResponse.json({ data: null, error: "Rate limit exceeded" }, { status: 429 });

  const body = await req.json().catch(() => null);
  const parsed = PushSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ data: null, error: "Invalid input", details: parsed.error.flatten() }, { status: 400 });
  }

  const admin = createAdminClient();

  const { data: project } = await admin
    .from("projects").select("id, name").eq("id", projectId).eq("user_id", user.id).single();
  if (!project) return NextResponse.json({ data: null, error: "Project not found" }, { status: 404 });

  // Load GitHub connection
  const { data: ghConn } = await admin
    .from("github_connections").select("token_enc, login").eq("user_id", user.id).single();

  // Fall back to server-level GitHub token
  const token = ghConn?.token_enc
    ? await decryptSecret(ghConn.token_enc as string).catch(() => null)
    : process.env.GITHUB_TOKEN ?? null;

  if (!token) {
    return NextResponse.json({ data: null, error: "No GitHub token configured. Add one in Settings → Providers." }, { status: 400 });
  }

  const octokit = new Octokit({ auth: token });

  // Get authenticated user
  const { data: ghUser } = await octokit.users.getAuthenticated();

  // Load project files
  const { data: files } = await admin
    .from("project_files").select("path, content")
    .eq("project_id", projectId).eq("is_deleted", false);

  if (!files || files.length === 0) {
    return NextResponse.json({ data: null, error: "No files to push" }, { status: 400 });
  }

  try {
    // Create or get repo
    let repoUrl: string;
    let sha: string | undefined;

    try {
      const { data: existingRepo } = await octokit.repos.get({
        owner: ghUser.login, repo: parsed.data.repoName,
      });
      repoUrl = existingRepo.html_url;
    } catch {
      const { data: newRepo } = await octokit.repos.createForAuthenticatedUser({
        name:        parsed.data.repoName,
        description: parsed.data.description ?? (project.name as string),
        private:     parsed.data.isPrivate,
        auto_init:   false,
      });
      repoUrl = newRepo.html_url;
    }

    // Build tree
    const treeItems = await Promise.all(
      files.map(async (file) => {
        const cleanPath = (file.path as string).startsWith("/") ? (file.path as string).slice(1) : (file.path as string);
        const { data: blob } = await octokit.git.createBlob({
          owner: ghUser.login, repo: parsed.data.repoName,
          content: Buffer.from((file.content ?? "") as string).toString("base64"),
          encoding: "base64",
        });
        return { path: cleanPath, mode: "100644" as const, type: "blob" as const, sha: blob.sha };
      })
    );

    // Get base tree SHA (if repo exists and has commits)
    let baseTreeSha: string | undefined;
    try {
      const { data: ref } = await octokit.git.getRef({
        owner: ghUser.login, repo: parsed.data.repoName, ref: `heads/${parsed.data.branch}`,
      });
      const { data: commit } = await octokit.git.getCommit({
        owner: ghUser.login, repo: parsed.data.repoName, commit_sha: ref.object.sha,
      });
      baseTreeSha = commit.tree.sha;
      sha = ref.object.sha;
    } catch { /* new repo — no base tree */ }

    const { data: tree } = await octokit.git.createTree({
      owner: ghUser.login, repo: parsed.data.repoName,
      tree: treeItems,
      ...(baseTreeSha ? { base_tree: baseTreeSha } : {}),
    });

    const { data: newCommit } = await octokit.git.createCommit({
      owner: ghUser.login, repo: parsed.data.repoName,
      message: `feat: generated by AgentForge — ${new Date().toISOString()}`,
      tree: tree.sha,
      ...(sha ? { parents: [sha] } : {}),
    });

    // Create or update branch ref
    try {
      await octokit.git.updateRef({
        owner: ghUser.login, repo: parsed.data.repoName,
        ref: `heads/${parsed.data.branch}`, sha: newCommit.sha, force: true,
      });
    } catch {
      await octokit.git.createRef({
        owner: ghUser.login, repo: parsed.data.repoName,
        ref: `refs/heads/${parsed.data.branch}`, sha: newCommit.sha,
      });
    }

    // Persist connection info
    await admin.from("github_connections").upsert({
      user_id:    user.id,
      login:      ghUser.login,
      token_enc:  ghConn?.token_enc ?? "",
      repo_url:   repoUrl,
      commit_sha: newCommit.sha,
      updated_at: new Date().toISOString(),
    }, { onConflict: "user_id" }).catch(() => {});

    return NextResponse.json({
      data: { repoUrl, commitSha: newCommit.sha, fileCount: files.length, branch: parsed.data.branch },
      error: null,
    });

  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ data: null, error: `GitHub push failed: ${message}` }, { status: 500 });
  }
}
